### ISSUE TITLE
Make fallback optional

### ISSUE THREAD

**Issue by russellbanks** [WonderzGmbH/nativefiledialog-java#11]
As title, the fallback should be optional/nullable.

This is useful for cases when the user can't or doesn't want to provide a window component. The result should just be `FileDialogResult.Error` in this case.

**Comment by AChep** [comment]
If you don't want the fallback you can construct `NfdFileDialog` directly. 

```
val nfd = NfdFileDialog()
```

I guess this should also be added to the README.md :+1:
