### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by russellbanks** [WonderzGmbH/nativefiledialog-java#4]
It would be great if this library could be published to Maven Central so I can include it in my project!

**Comment by AChep** [comment]
Nice to see that people are interested in this project! I'll bring this up internally, it would be amazing to have it available there.

**Comment by russellbanks** [comment]
@AChep is there any update this/other issues? I'd love to include it in [russellbanks/HashHash](https://github.com/russellbanks/HashHash)!

**Comment by AChep** [comment]
@russellbanks I'll try to work on these this week :)

**Comment by AChep** [comment]
@russellbanks yay, it should be available here! :) https://central.sonatype.com/artifact/tv.wunderbox/nativefiledialog/1.0.2
