### ISSUE TITLE
Remove Arrow dependency

### ISSUE THREAD

**Issue by russellbanks** [WonderzGmbH/nativefiledialog-java#8]
Transitive dependencies should be minimal in libraries. Ideally, the only dependency that we should have for this project is JNA.

By the looks of it, Arrow is mainly used for the Either sealed class. This could be replaced with a custom sealed class, a pair (least preferable), or Kotlin's [Result](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result) class.

**Comment by AChep** [comment]
Fixed by https://github.com/WonderzGmbH/nativefiledialog-java/commit/ab79fc940e8736cf0f977b1bccc1d9ee99edf4ec
