### ISSUE TITLE
Rename project indicating JVM or Kotlin

### ISSUE THREAD

**Issue by russellbanks** [WonderzGmbH/nativefiledialog-java#9]
Kotlin developers tend to look for Kotlin libraries for null-safety, etc. Without looking at the source or the language breakdown, the name of the project seems oriented to Java projects. A name that indicates Kotlin or the JVM in general would be more suitable. Further to this, a push on a Compose for Desktop use case would be good to develop in the ReadMe.

**Comment by AChep** [comment]
Added a comment on how to use with Compose. I think that's enough, because the project itself might also be used with any other JVM framework.
